#  ____  _            _______ _          _____
# |  _ \| |          |__   __| |        |  __ \
# | |_) | | __ _ _______| |  | |__   ___| |  | | _____   __
# |  _ <| |/ _` |_  / _ \ |  | '_ \ / _ \ |  | |/ _ \ \ / /
# | |_) | | (_| |/ /  __/ |  | | | |  __/ |__| |  __/\ V /
# |____/|_|\__,_/___\___|_|  |_| |_|\___|_____/ \___| \_/

# BlazinFly Configuration File:
# Use the § symbol for color coding.
#   Default Config:
#      onJoin-FlyReset: true
#      onDamage-FlyReset: true
#      fly-enabled: "Flight mode activated"
#      fly-disabled: "Flight mode deactivated"

# The below config allows the plugin to reset flight mode when joining the server
onJoin-FlyReset: true

# The below config allows the plugin to reset flight mode when pvping in the server
onDamage-FlyReset: true

# The below config allows you to send a message to the player when they enable fly
fly-enabled: "§aFlight mode activated"

# The below config allows you to send a message to the player when they disable fly
fly-disabled: "§cFlight mode deactivated"
...